# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

packages:
  - name: lib
    type: go
    deps:
      - components/common-go:lib
    srcs:
      - "**"
    config:
      packaging: library
      dontTest: false
  - name: app
    type: go
    deps:
      - components/common-go:lib
    srcs:
      - go.mod
      - go.sum
      - "**/*.go"
    env:
      - CGO_ENABLED=0
    config:
      packaging: app
      buildCommand: [
          "go",
          "build",
          "-trimpath",
          "-ldflags",
          # todo(sje): add the segment token from a leeway secret
          "-buildid= -w -s -X 'github.com/gitpod-io/gitpod/installation-telemetry/cmd.Version=commit-${__git_commit}' -X 'github.com/gitpod-io/gitpod/installation-telemetry/cmd.segmentIOToken=my-token'",
        ]
  - name: docker
    type: docker
    deps:
      - :app
    argdeps:
      - imageRepoBase
    config:
      buildArgs:
        VERSION: ${version}
      dockerfile: leeway.Dockerfile
      metadata:
        helm-component: installationTelemetry
      image:
        - ${imageRepoBase}/installation-telemetry:${version}
        - ${imageRepoBase}/installation-telemetry:commit-${__git_commit}
